FROM ruby:2.7.1

WORKDIR /usr/src/app

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get --yes install nodejs nano yarn

COPY Gemfile Gemfile.lock .ruby-gemset ./

RUN bundle install